exposes maps of network policies and conn_track to ingress/egress xdp progs
CentaurusInfra/mizar pull request #321
Opened 2020-12-21 18:56 UTC by h-w-chen

It fixes #304.

According to conn_track design of mizar network policy, in order to block the reply UDP packets after the policy updates and intends to block the originated udp traffic. Due to udp being one directional protocol in nature, the _logical_ reply packets could go without the _loogical_ originated packet; this imposes some difficulty for policy neforcement, as there might be no packet emitted on the _originally directed_ wire, and the policy enforcement at the other direction has to handle w/o the help from the _original direction_. The proposal in the design is, for udp reply packet of a tracked connection, it consults the relevant policies to decide whether the _originated_ packet should be allowed or denied; based the this decision, the reply packet will be allowed or denied, respectively.

This PR is part of the implementation of the proposal: it exposes ingress policies to egress enforcement prog, and vise versa. The change of xdp prog to consulte polices and decide whether the udp reply packet should be allowed or denied is in PR coming soon.

In the future implementation of conn_track, when tracked connections introduce states to differentaie being allowed or denied explicitly, the enforcement prog will disregard the state but relies on policy calculation when deciding where the reply packet should go or block.

2020-12-21 22:29 UTC, clu2xlu requested changes

2020-12-21 22:29 UTC, clu2xlu commented on src/dmn/trn_agent_xdp_usr.c
> +	    !md->conn_track_cache) {
Please also add fd

2020-12-21 22:37 UTC, h-w-chen commented on src/dmn/trn_agent_xdp_usr.c
> +	    !md->conn_track_cache) {
will fix.

2020-12-22 00:04 UTC, clu2xlu approved these changes

2020-12-22 00:05 UTC, merged